#
# Tokyo Night Custom theme
#
# Based on custom colors from wezterm.lua configuration
#

colors:
  # variable: "rrggbb" | source-names (if divergent)
  fg:        "CBE0F0"  # foreground
  bg:        "011423"  # background
  gray1:     "033259"  # selection_bg
  gray2:     "214969"  # ansi[0] (dark blue)
  gray3:     "214969"  # ansi[0] (dark blue) - for comments/muted
  red1:      "E52E2E"  # ansi[1] (red)
  red2:      "E52E2E"  # ansi[1] (red) - error
  orange:    "FFE073"  # ansi[3] (yellow/orange)
  yellow:    "FFE073"  # ansi[3] (yellow)
  green1:    "44FFB1"  # ansi[2] (green)
  green2:    "24EAF7"  # ansi[6] (cyan/teal)
  green3:    "44FFB1"  # ansi[2] (green)
  blue1:     "24EAF7"  # ansi[6] (bright cyan)
  blue2:     "0FC5ED"  # ansi[4] (blue)
  blue3:     "0FC5ED"  # ansi[4] (blue/info)
  blue4:     "24EAF7"  # ansi[6] (cyan)
  blue5:     "24EAF7"  # ansi[6] (cyan)
  blue6:     "0FC5ED"  # ansi[4] (blue)
  purple1:   "a277ff"  # ansi[5] (magenta/purple)
  purple2:   "a277ff"  # ansi[5] (magenta/purple)
  bg_red1:   "033259"
  bg_orange: "033259"
  bg_yellow: "033259"
  bg_green1: "033259"
  bg_green2: "033259"

core:
  normal_text:
    foreground: gray3
  regular_file: {}
  reset_to_normal:
    foreground: gray3
  directory:
    foreground: blue6
    font-style: bold
  executable_file:
    foreground: green1
    font-style: bold
  file_with_capability:
    background: gray1
  setuid:
    background: gray1
  setgid:
    background: gray1
  sticky:
    background: gray1
  sticky_other_writable:
    foreground: bg
    background: blue6
    font-style: bold
  other_writable:
    foreground: blue6
    background: gray1
    font-style: bold
  symlink:
    foreground: blue4
    font-style: italic
  broken_symlink:
    foreground: bg
    background: red2
  missing_symlink_target:
    foreground: red2
  multi_hard_link: {}
  socket:
    foreground: green2
    background: bg_green2
    font-style: bold
  fifo:
    foreground: orange
    background: bg_orange
    font-style: bold
  door:
    foreground: green1
    background: bg_green1
    font-style: bold
  block_device:
    foreground: red1
    background: bg_red1
    font-style: bold
  character_device:
    foreground: yellow
    background: bg_yellow
    font-style: bold

executable:
  foreground: green2

archives:
  foreground: red1
  font-style: bold

media:
  audio:
    foreground: blue3
    font-style: bold
  image:
    foreground: purple1
    font-style: bold
  video:
    foreground: green3
    font-style: bold
  fonts:
    foreground: green2
    font-style: bold
  3d:
    foreground: purple1
    font-style: bold

office:
  foreground: purple2
  font-style: bold

text:
  foreground: fg
  configuration:
    foreground: orange
    dockerfile:
      foreground: blue2
  licenses:
    foreground: fg
    font-style: bold
  special:
    foreground: blue5
    font-style: bold
  todo:
    foreground: blue1
    font-style: bold

markup:
  foreground: fg

programming:
  foreground: yellow
  tooling:
    foreground: blue3
    continuous-integration:
      foreground: blue2

unimportant:
  foreground: gray2

